### ISSUE TITLE
关于 【分享 Vim 插件：UltiSnips 让 Vim 飞起来 】

### ISSUE THREAD

**Issue by ProtossGenius** [xiaoronglv/xiaoronglv.github.io#4]
请问如何设置优先级？
假如自己定义的快捷键和 honza/vim-snippets 的冲突了，vim会提示选择文件，我希望它默认选择高优先级的。

**Comment by xiaoronglv** [comment]
我已经叛变了，我现在用 jetbrains 全家桶 + vim 插件
